name: Ping Pong CI/CD

on:
push:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - uses: actions/checkout@v3

  - name: Build Frontend
    run: docker build -t pingpong-frontend ./frontend

  - name: Build Backend
    run: docker build -t pingpong-backend ./backend
```
